### ISSUE TITLE
Exclude candidates in `get_dependencies` of the DependencyProvider

### ISSUE THREAD

**Issue by tdejager** [mamba-org/resolvo#14]
# Description

It would be a really nice feature if we have a way to exclude candidates when getting their dependencies. 
With pypi packages for example it's possible that you are able to get the candidates for a Solvable but that it is impossible to get the dependencies for this candidate. 

With pypi packages, specifically in the case of source distributions, you might not be able to get the metadata because you have to build the source, which might fail. It would be nice to be able to exclude this candidate at this point.

However, we would need to think how to best handle this, as backtracking might not be interesting. Take the case where you want to have `pygame` as a dependency for example, this depends on `sdl2`, should this source build fail because `sdl2` is missing. Backtracking will take long (because it has to build everything) and would not produce any good results. I think aborting the solve in this case would be best. However, there might be situations where an older build would work, idk, maybe backtracking does make sense.

# Prior art

When looking at pubgrub, specifically: https://github.com/pubgrub-rs/pubgrub/blob/717289be5722dd5caaa0d1f4ed13047d11a7f7fd/src/solver.rs#L141C8-L153C21

It seems there are 2 options for `get_dependencies`, there is a `Result` that makes the solver abort the current resolution. But also a `Dependencies::Unknown` enum that adds an `incompatibility` to the solver.

**Comment by wolfv** [comment]
I think regarding the backtracking – it should generally always make sense to test more versions. The main thing is that we need to provide a good UI / UX to the user so that they would see exactly the error (I think pip also shows it during the resolving).

Then the user could cancel the testing of more versions by using CTRL+C and specify a different version of pygame / SDL2 / etc.

On the other hand, it could be interesting to add a 'stop' function to resolvo (e.g. by timeout or by some other condition that the developer could implement). resolvo could call that function at every iteration and stop iterating if it evaluates to true (but IMO that's another issue #8).

**Comment by wolfv** [comment]
To expand a bit on this issue and provide some more context: in the `DependencyProvider` we return the `Dependencies`, but not a Result or `enum`. So we have no way to bubble up some problem if none of the dependencies can be used.

Here is the code in rip that causes a `panic!` that we would love to get rid of:

https://github.com/prefix-dev/rip/blob/25e2344e62804dab039a1c806b7489c3779f3e47/crates/rattler_installs_packages/src/resolve/dependency_provider.rs#L466-L479
