### ISSUE TITLE
Add a "timeout" parameter or other stop conditions

### ISSUE THREAD

**Issue by wolfv** [mamba-org/resolvo#8]
One thing that would be nice is to be able to configure "stop" conditions for the solver.

E.g. to be able to say:

- if you don't find a solution after 5 seconds, give up and return a TimeoutError
- if you have looped 300k times, stop and return a MaxIterationError

That's something we could never do with `libsolv`, so would be nice to have!

**Comment by Eh2406** [comment]
In pubgrub-rs we added a [`should_cancel`](https://docs.rs/pubgrub/latest/pubgrub/solver/trait.DependencyProvider.html#method.should_cancel) to our DependencyProvider Trait, so that the user could configure their own timeout mechanism. If `resolvo` comes up with something better I would be happy to copy it in pubgrub-rs.
